version: 1.0

############################################################
# +------------------------------------------------------+ #
# |                     Persistance                      | #
# +------------------------------------------------------+ #
############################################################

storageType: FILE